name: passdi_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  dotted_line: ^3.1.0
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.0.2
  flutter_html: ^2.2.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.6.1
  font_awesome_flutter: ^10.3.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  google_fonts: ^4.0.1
  google_maps_flutter: ^2.2.5
  json_annotation: ^4.8.0
  nb_utils: ^5.0.4
  permission_handler: ^10.2.0
  search_map_place_updated: ^0.0.4
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mobx: ^2.1.4

flutter_assets:
  assets_path: assets/
  output_path: lib/app/assets
  package: module_home
  compress_images: false

flutter:
  uses-material-design: true

  assets:
    - assets/misc/
